name: Build and deploy frontend to Firebase Hosting

on:
  push:
    branches: [ Front-end ]
  pull_request:
    branches: [ Front-end ]

jobs:
  build:
    name: Build web artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install
      working-directory: zarahealth
    - run: npm run build
      working-directory: zarahealth
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_PATH: zarahealth